version: "3.9"
services:
  chat-server:
    build: .
    container_name: chat-server
    ports:
      - "8080:8080"
    volumes:
      - ./chat.db:/app/chat.db   # persiste la base SQLite
    restart: unless-stopped
